import { montserrat, poppins } from "@/helpers/fonts";
import "../global.scss";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

export const metadata = {
	title: {
		template: "%s | Cosmo Shop",
		default: "Cosmo Shop",
	},
	description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const session = await auth();

	return (
		<html
			lang="en"
			className={`${montserrat.variable} ${poppins.variable}`}
		>
			<body
				suppressHydrationWarning={true}
				className={`d-flex flex-column justify-content-between vh-100`}
			>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
